# Generated by Django 3.2.5 on 2022-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20220215_1900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conf',
            options={'ordering': ['-visibleTime']},
        ),
        migrations.AddField(
            model_name='conf',
            name='heading',
            field=models.TextField(default=' '),
        ),
    ]
