# Generated by Django 3.2.5 on 2022-02-18 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_alter_conf_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='heading',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='conf',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('conf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.conf')),
            ],
        ),
    ]
