# Generated by Django 3.2.5 on 2022-02-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20220218_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='conf',
        ),
        migrations.AddField(
            model_name='comment',
            name='id_conf',
            field=models.IntegerField(default=0),
        ),
    ]
